use rand::prelude::*;
use rand_xoshiro::Xoshiro256PlusPlus as Rng64;
use std::sync::Mutex;

use crate::callbacks::{EvalCallbacks, GameCallbacks};

/// Random rollout evaluator.
///
/// Clones the game state and plays random moves until a terminal state,
/// then returns the terminal value as the evaluation. Works entirely
/// in Rust with no cross-language callback overhead during the rollout
/// (only uses `GameCallbacks` methods on the cloned state).
///
/// Requires that games have terminal states (i.e., `available_moves()`
/// eventually returns an empty vec).
///
/// When created with `new()`, uses `thread_rng()` for lock-free parallel search.
/// When created with `with_seed()`, uses a shared seeded RNG for deterministic
/// single-threaded replay (Mutex serializes parallel access).
pub struct RandomRollout {
    rng: Option<Mutex<Rng64>>,
}

impl RandomRollout {
    pub fn new() -> Self {
        Self { rng: None }
    }

    pub fn with_seed(seed: u64) -> Self {
        Self {
            rng: Some(Mutex::new(Rng64::seed_from_u64(seed))),
        }
    }
}

impl Default for RandomRollout {
    fn default() -> Self {
        Self::new()
    }
}

impl EvalCallbacks for RandomRollout {
    fn evaluate(&self, state: &dyn GameCallbacks, moves: &[String]) -> (Vec<f64>, f64) {
        // No priors (uniform will be generated by the adapter)
        let priors = Vec::new();

        if moves.is_empty() {
            // Already terminal
            return (priors, 0.0);
        }

        // Clone the state and play random moves until terminal
        let mut sim = state.clone_box();
        let max_depth = 1000;

        for _ in 0..max_depth {
            let available = sim.available_moves();
            if available.is_empty() {
                break;
            }
            let idx = match &self.rng {
                Some(mutex_rng) => {
                    let mut rng = mutex_rng.lock().unwrap();
                    rng.gen_range(0..available.len())
                }
                None => {
                    let mut rng = rand::thread_rng();
                    rng.gen_range(0..available.len())
                }
            };
            sim.make_move(&available[idx]);
        }

        // Try to get a terminal value
        if let Some(pv) = sim.terminal_value() {
            let value = match pv {
                treant::ProvenValue::Win => 1.0,
                treant::ProvenValue::Loss => -1.0,
                treant::ProvenValue::Draw => 0.0,
                treant::ProvenValue::Unknown => 0.0,
            };
            // Value is from the perspective of the player at the terminal state.
            // We need it from the perspective of the player at the evaluated state.
            let eval_player = state.current_player();
            let terminal_player = sim.current_player();
            if eval_player == terminal_player {
                (priors, value)
            } else {
                (priors, -value)
            }
        } else {
            (priors, 0.0)
        }
    }
}
